version: "3"
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/node.conf:/etc/nginx/conf.d/node.template
      - ./nginx/my-site.com.crt:/etc/ssl/certs/my-site.com.crt
      - ./nginx/my-site.com.key:/etc/ssl/private/my-site.com.key
    ports:
      - '8080:80'
      - '8085:443'
    command: 'bash -c "cat /etc/nginx/conf.d/node.template > /etc/nginx/conf.d/default.conf && nginx -g ''daemon off;''"'
    networks:
      - proxy
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - database:/data/db
    networks:
      - proxy
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    networks:
      - proxy
  react:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    volumes:
      - ./client:/client
      - /client/node_modules
    depends_on:
      - "server"
    networks:
      - proxy
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./server:/server
      - /server/node_modules
    depends_on:
      - "mongo"
    networks:
      - proxy
networks:
  proxy:
    external: true

volumes:
  database:
